name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: recursive
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy
      - name: Configure
        run: cmake -B build
      - name: Compile
        run: cmake --build build -j $(nproc)
      - name: Run tests
        run: ctest --test-dir build --output-on-failure --verbose
